import { Claim } from "./types";

export const initialClaims: Claim[] = [
  {
    id: "claim-1",
    code: "WAHA-26-109",
    title: "Wellhead Maintenance - Phase II",
    company: "Waha Oil Company",
    companyId: "WAHA",
    wbs: "WAHA-26-109",
    claimedValue: "$33,676,417",
    numericValue: 33676417,
    submittedBy: "Eng. Tarek El-Fassi",
    submissionDate: "October 24, 2026 09:15 AM",
    previousProgress: 45.0,
    claimedProgress: 62.5,
    priority: "high",
    dueDate: "Today",
    previousNotes: "Mechanical completion of Phase I verified. Electrical interconnections are pending final loop testing before advancing beyond 45%. - October 10, 2026",
    deliverables: [
      {
        id: "del-1-1",
        description: "Complete electrical wiring hookups (Wells 14-18)",
        weight: "10.0%",
        status: "completed",
      },
      {
        id: "del-1-2",
        description: "Pressure test sign-off (QA/QC Dept)",
        weight: "5.0%",
        status: "completed",
      },
      {
        id: "del-1-3",
        description: "Site demobilization preparation",
        weight: "2.5%",
        status: "pending",
      },
    ],
    documents: [
      {
        id: "doc-1-form2",
        name: "Form_2_Certificate_Of_Conformity_WAHA-26-109.pdf",
        size: "1.5 MB",
        uploadedAt: "09:12 AM",
        type: "PDF",
        url: "/noc_vault/evidence/Form_2_Certificate_Of_Conformity_WAHA-26-109.pdf",
      },
      {
        id: "doc-1-form4",
        name: "Form_4_Technical_Approval_WAHA-26-109.pdf",
        size: "1.2 MB",
        uploadedAt: "09:14 AM",
        type: "PDF",
        url: "/noc_vault/evidence/Form_4_Technical_Approval_WAHA-26-109.pdf",
        document_type: "technical_approval_form"
      },
      {
        id: "doc-1-1",
        name: "QAQC_Signoff_Wells14-18.pdf",
        size: "2.4 MB",
        uploadedAt: "09:10 AM",
        type: "PDF",
      },
      {
        id: "doc-1-2",
        name: "Progress_Measurement_Sheet_Oct.xlsx",
        size: "850 KB",
        uploadedAt: "09:12 AM",
        type: "XLSX",
      },
      {
        id: "doc-1-3",
        name: "Site_Photo_TieIn_Complete.jpg",
        size: "4.1 MB",
        uploadedAt: "09:14 AM",
        type: "IMAGE",
        url: "https://lh3.googleusercontent.com/aida-public/AB6AXuCBZO1wG_qTW9XLoXNcznnSQgbs4e8ez-KDVUHGDAAbEYHF8wDzJYk6fn4S1KIx0-bXpvE23YX_vq9tEyudiSmkotFuwrE8fnQNNZf391uNH-es6OmiSmWBWcvbnDJik6FkUrG1fvo3HNvs7R0YLmAx_OfANRM_TjXiachEv6E87tTVcYL4MEiufFsntpSRem8FwWC8bYiNxQC1t9kpTG22wBvQ8zxb6nU-eYqfB7FnZcPcB-GYAM6T1A",
      },
    ],
    auditLog: [
      {
        id: "log-1-1",
        user: "Eng. Tarek El-Fassi",
        action: "Submission",
        change: "45.0% → 62.5%",
        timestamp: "Oct 24, 09:15 AM",
      },
      {
        id: "log-1-2",
        user: "System Validator",
        action: "Verification",
        change: "Automated check on all PDF attachments & certificates passed",
        timestamp: "Oct 24, 09:16 AM",
      },
    ],
    auditorNotes: "",
    status: "pending_financial_audit",
    invoiceNumber: "INV-WAHA-26-109",
    invoiceAmount: 781250,
  },
  {
    id: "claim-2",
    code: "AGOCO-26-042",
    title: "Pipeline Route Survey - Block NC-41",
    company: "Arabian Gulf Oil Company",
    companyId: "AGOCO",
    wbs: "AGOCO-26-042",
    claimedValue: "$12,123,510",
    numericValue: 12123510,
    submittedBy: "Eng. Salem Al-Obeidi",
    submissionDate: "October 23, 2026 11:30 AM",
    previousProgress: 20.0,
    claimedProgress: 35.0,
    priority: "standard",
    dueDate: "Tomorrow",
    previousNotes: "Initial terrain scan and basic corridor coordinates for the onshore pipeline branch completed successfully.",
    deliverables: [
      {
        id: "del-2-1",
        description: "Complete geophysical survey for main hub pathway",
        weight: "12.0%",
        status: "completed",
      },
      {
        id: "del-2-2",
        description: "Submit preliminary geotechnical soil report for review",
        weight: "3.0%",
        status: "pending",
      },
    ],
    documents: [
      {
        id: "doc-2-form3",
        name: "Form_3_Payment_Authorization_INV-AGOCO-26-042.pdf",
        size: "1.4 MB",
        uploadedAt: "11:20 AM",
        type: "PDF",
        url: "/noc_vault/evidence/Form_3_Payment_Authorization_INV-AGOCO-26-042.pdf",
        document_type: "general"
      },
      {
        id: "doc-2-form2",
        name: "Form_2_Certificate_Of_Conformity_AGOCO-26-042.pdf",
        size: "1.5 MB",
        uploadedAt: "10:05 AM",
        type: "PDF",
        url: "/noc_vault/evidence/Form_2_Certificate_Of_Conformity_AGOCO-26-042.pdf",
      },
      {
        id: "doc-2-form4",
        name: "Form_4_Technical_Approval_AGOCO-26-042.pdf",
        size: "1.2 MB",
        uploadedAt: "11:15 AM",
        type: "PDF",
        url: "/noc_vault/evidence/Form_4_Technical_Approval_AGOCO-26-042.pdf",
        document_type: "technical_approval_form"
      },
      {
        id: "doc-2-1",
        name: "Geotechnical_Draft_NC41.pdf",
        size: "5.1 MB",
        uploadedAt: "11:10 AM",
        type: "PDF",
      },
      {
        id: "doc-2-2",
        name: "Route_Mapping_Coordinates.xlsx",
        size: "1.2 MB",
        uploadedAt: "11:18 AM",
        type: "XLSX",
      },
    ],
    auditLog: [
      {
        id: "log-2-2",
        user: "Mr. Abdelrahman Boufardis",
        action: "Pre-Approve",
        change: "Compliance verified & pre-approved for payment. Sent to NOC Head of Accounts.",
        timestamp: "Oct 24, 10:30 AM",
      },
      {
        id: "log-2-1",
        user: "Eng. Salem Al-Obeidi",
        action: "Submission",
        change: "20.0% → 35.0%",
        timestamp: "Oct 23, 11:30 AM",
      },
    ],
    auditorNotes: "Pipeline route survey coordinates verified. Invoice matches the certified progress value within limits.",
    status: "pending_head_of_accounts_approval",
    invoiceNumber: "INV-AGOCO-26-042",
    invoiceAmount: 157500,
  },
  {
    id: "claim-3",
    code: "ZALLAF-26-008",
    title: "Erawin Field - Substation Civil Works",
    company: "Zallaf Libya",
    companyId: "ZALLAF",
    wbs: "ZALLAF-26-008",
    claimedValue: "$23,977,609",
    numericValue: 23977609,
    submittedBy: "Eng. Muftah Al-Warfali",
    submissionDate: "October 22, 2026 02:20 PM",
    previousProgress: 55.0,
    claimedProgress: 72.0,
    priority: "standard",
    dueDate: "Oct 28",
    previousNotes: "Reinforced concrete foundations for ground generators poured. Waiting for 28-day concrete cube compressive strength test report.",
    deliverables: [
      {
        id: "del-3-1",
        description: "Pour concrete bases for primary transformers & heavy gear",
        weight: "15.0%",
        status: "completed",
      },
      {
        id: "del-3-2",
        description: "Erect boundary blast walls and oil containment sumps",
        weight: "2.0%",
        status: "pending",
      },
    ],
    documents: [
      {
        id: "doc-3-1",
        name: "Concrete_Compressive_Strength_Report.pdf",
        size: "1.8 MB",
        uploadedAt: "02:05 PM",
        type: "PDF",
      },
      {
        id: "doc-3-2",
        name: "Substation_Foundations_Drawing.pdf",
        size: "3.5 MB",
        uploadedAt: "02:12 PM",
        type: "PDF",
      },
    ],
    auditLog: [
      {
        id: "log-3-1",
        user: "Eng. Muftah Al-Warfali",
        action: "Submission",
        change: "55.0% → 72.0%",
        timestamp: "Oct 22, 02:20 PM",
      },
    ],
    auditorNotes: "",
    status: "authorized_for_payment",
    invoiceNumber: "INV-ZALLAF-26-008",
    invoiceAmount: 30254958,
    paymentToken: "NOC-AUTH-HQ-9012-claim-3",
  },
  {
    id: "claim-4",
    code: "MELLITAH-26-211",
    title: "Gas Processing Plant Overhaul",
    company: "Mellitah Oil & Gas",
    companyId: "MELLITAH",
    wbs: "MELLITAH-26-211",
    claimedValue: "$91,599,856",
    numericValue: 91599856,
    submittedBy: "Eng. Ali Al-Zway",
    submissionDate: "October 21, 2026 10:00 AM",
    previousProgress: 70.0,
    claimedProgress: 85.0,
    priority: "standard",
    dueDate: "Oct 29",
    previousNotes: "Overhaul on main gas compressors and valve isolations completed on Units 1 & 2. Pre-commissioning leak tests in progress.",
    deliverables: [
      {
        id: "del-4-1",
        description: "Install automatic control valves & update Unit PLC logic",
        weight: "12.0%",
        status: "completed",
      },
      {
        id: "del-4-2",
        description: "Perform Nitrogen leak testing on separator vessel circuits",
        weight: "3.0%",
        status: "pending",
      },
    ],
    documents: [
      {
        id: "doc-4-1",
        name: "PLC_Upgrade_Checklist.pdf",
        size: "3.2 MB",
        uploadedAt: "09:50 AM",
        type: "PDF",
      },
      {
        id: "doc-4-2",
        name: "Nitrogen_Leak_Test_Protocol.pdf",
        size: "2.1 MB",
        uploadedAt: "09:55 AM",
        type: "PDF",
      },
    ],
    auditLog: [
      {
        id: "log-4-1",
        user: "Eng. Ali Al-Zway",
        action: "Submission",
        change: "70.0% → 85.0%",
        timestamp: "Oct 21, 10:00 AM",
      },
    ],
    auditorNotes: "",
    status: "pending_financial_audit",
    invoiceNumber: "INV-MELLITAH-26-211",
    invoiceAmount: 2890000,
  },
  {
    id: "claim-5",
    code: "WAHA-26-112",
    title: "Offshore Gas Lift Compression Package",
    company: "Waha Oil Company",
    companyId: "WAHA",
    wbs: "WAHA-26-112",
    claimedValue: "$130,664,500",
    numericValue: 130664500,
    submittedBy: "Eng. Khaled Belhaj",
    submissionDate: "October 20, 2026 11:15 AM",
    previousProgress: 10.0,
    claimedProgress: 30.0,
    priority: "high",
    dueDate: "Oct 30",
    previousNotes: "Gas compressor skid structures completed fabrication. Pending hydraulic system integration and shipping manifests to offshore platform.",
    deliverables: [
      {
        id: "del-5-1",
        description: "Compressor skid mainframe fabrication & NDT inspection",
        weight: "15.0%",
        status: "completed",
      },
      {
        id: "del-5-2",
        description: "Procurement certificate submission for gas turbines",
        weight: "5.0%",
        status: "completed",
      },
    ],
    documents: [
      {
        id: "doc-5-1",
        name: "Skid_NDT_Testing_Report.pdf",
        size: "4.8 MB",
        uploadedAt: "11:00 AM",
        type: "PDF",
      },
      {
        id: "doc-5-2",
        name: "Turbine_Procurement_Verification.pdf",
        size: "3.1 MB",
        uploadedAt: "11:05 AM",
        type: "PDF",
      },
    ],
    auditLog: [
      {
        id: "log-5-1",
        user: "Eng. Khaled Belhaj",
        action: "Submission",
        change: "10.0% → 30.0%",
        timestamp: "Oct 20, 11:15 AM",
      },
      {
        id: "log-5-2",
        user: "System Validator",
        action: "Automated Flags",
        change: "Warning: Missing offshore logistics customs clearance certification.",
        timestamp: "Oct 20, 11:17 AM",
      },
    ],
    auditorNotes: "Customs and transit documentation for offshore installation must be uploaded. Put on hold pending clarification.",
    status: "info_requested",
    invoiceNumber: "INV-WAHA-26-112",
    invoiceAmount: 1455000,
  },
  {
    id: "claim-6",
    code: "AGOCO-26-055",
    title: "Sarir Field Water Injection System Upgrade",
    company: "Arabian Gulf Oil Company",
    companyId: "AGOCO",
    wbs: "AGOCO-26-055",
    claimedValue: "$49,841,098",
    numericValue: 49841098,
    submittedBy: "Eng. Mustafa Al-Majri",
    submissionDate: "October 19, 2026 03:45 PM",
    previousProgress: 35.0,
    claimedProgress: 55.0,
    priority: "standard",
    dueDate: "Nov 02",
    previousNotes: "Water intake line layed. Flow control valves calibrated. Pressure pump station Civil foundations are 100% complete.",
    deliverables: [
      {
        id: "del-6-1",
        description: "Intake pipeline laying (Kms 0-12) & tie-ins complete",
        weight: "15.0%",
        status: "completed",
      },
      {
        id: "del-6-2",
        description: "Flow control valve instrumentation calibration sheets",
        weight: "5.0%",
        status: "completed",
      },
    ],
    documents: [
      {
        id: "doc-6-1",
        name: "Sarir_Water_Injection_Valves_Calibration.pdf",
        size: "2.9 MB",
        uploadedAt: "03:30 PM",
        type: "PDF",
      },
      {
        id: "doc-6-2",
        name: "Sarir_Pipeline_Alignment_Sheet.xlsx",
        size: "3.6 MB",
        uploadedAt: "03:40 PM",
        type: "XLSX",
      },
    ],
    auditLog: [
      {
        id: "log-6-1",
        user: "Eng. Mustafa Al-Majri",
        action: "Submission",
        change: "35.0% → 55.0%",
        timestamp: "Oct 19, 03:45 PM",
      },
    ],
    auditorNotes: "",
    status: "pending_financial_audit",
    invoiceNumber: "INV-AGOCO-26-055",
    invoiceAmount: 1017500,
  },
  {
    id: "claim-7",
    code: "ZALLAF-26-015",
    title: "Shaddad Field Early Production Facility (EPF)",
    company: "Zallaf Libya",
    companyId: "ZALLAF",
    wbs: "ZALLAF-26-015",
    claimedValue: "$167,035,031",
    numericValue: 167035031,
    submittedBy: "Eng. Reda Al-Ghariani",
    submissionDate: "October 18, 2026 08:30 AM",
    previousProgress: 80.0,
    claimedProgress: 95.0,
    priority: "high",
    dueDate: "Nov 05",
    previousNotes: "Pre-commissioning trials with live crude completed. Production separator vessel functioning under nominal conditions.",
    deliverables: [
      {
        id: "del-7-1",
        description: "Separator vessel live-stream hot commissioning & test logs",
        weight: "10.0%",
        status: "completed",
      },
      {
        id: "del-7-2",
        description: "Safety shut-down (ESD) trip loops verification run",
        weight: "5.0%",
        status: "completed",
      },
    ],
    documents: [
      {
        id: "doc-7-1",
        name: "ESD_Trip_Loop_Testing_Log.pdf",
        size: "1.5 MB",
        uploadedAt: "08:15 AM",
        type: "PDF",
      },
      {
        id: "doc-7-2",
        name: "EPF_Commissioning_Hot_Run_Approval.pdf",
        size: "4.2 MB",
        uploadedAt: "08:22 AM",
        type: "PDF",
      },
    ],
    auditLog: [
      {
        id: "log-7-1",
        user: "Eng. Reda Al-Ghariani",
        action: "Submission",
        change: "80.0% → 95.0%",
        timestamp: "Oct 18, 08:30 AM",
      },
      {
        id: "log-7-2",
        user: "Mr. Abdelrahman Boufardis",
        action: "Pre-Approve",
        change: "Compliance checks complete. Passed to Head of Accounts.",
        timestamp: "Oct 19, 11:20 AM",
      },
    ],
    auditorNotes: "High priority EPF project nearing completion. Verified ESD trip test report and hot-run safety clearance parameters.",
    status: "pending_head_of_accounts_approval",
    invoiceNumber: "INV-ZALLAF-26-015",
    invoiceAmount: 5890000,
  },
  {
    id: "claim-8",
    code: "MELLITAH-26-219",
    title: "Bahr Essalam Gas Field - Platform Deck Refurbishment",
    company: "Mellitah Oil & Gas",
    companyId: "MELLITAH",
    wbs: "MELLITAH-26-219",
    claimedValue: "$56,576,381",
    numericValue: 56576381,
    submittedBy: "Eng. Younis Al-Fitouri",
    submissionDate: "October 17, 2026 11:10 AM",
    previousProgress: 15.0,
    claimedProgress: 30.0,
    priority: "standard",
    dueDate: "Nov 08",
    previousNotes: "Scaffolding erection for structural sandblasting and anti-corrosion primer application on Deck C is 100% complete.",
    deliverables: [
      {
        id: "del-8-1",
        description: "Scaffolding system certification for sub-sea deck areas",
        weight: "10.0%",
        status: "completed",
      },
      {
        id: "del-8-2",
        description: "Sandblasting of structural girders & primer coats Deck C",
        weight: "5.0%",
        status: "completed",
      },
    ],
    documents: [
      {
        id: "doc-8-1",
        name: "DeckC_Scaffolding_Safety_Signoff.pdf",
        size: "3.7 MB",
        uploadedAt: "10:55 AM",
        type: "PDF",
      },
      {
        id: "doc-8-2",
        name: "AntiCorrosion_Primer_Batch_Specs.pdf",
        size: "1.9 MB",
        uploadedAt: "11:02 AM",
        type: "PDF",
      },
    ],
    auditLog: [
      {
        id: "log-8-1",
        user: "Eng. Younis Al-Fitouri",
        action: "Submission",
        change: "15.0% → 30.0%",
        timestamp: "Oct 17, 11:10 AM",
      },
    ],
    auditorNotes: "Scaffolding structural sign-off verified by platform safety officer. Anti-corrosion compliance certificates attached.",
    status: "authorized_for_payment",
    invoiceNumber: "INV-MELLITAH-26-219",
    invoiceAmount: 29745042,
    paymentToken: "NOC-AUTH-HQ-9931-claim-8",
  },
  {
    id: "claim-sirte-1",
    code: "SIRTE-26-001",
    title: "Gas Pipeline & Compressor Station Upgrades - Executing Phase",
    company: "Sirte Oil Company",
    companyId: "SIRTE",
    wbs: "3.0",
    claimedValue: "$9,429,397",
    numericValue: 9429397,
    submittedBy: "Eng. Salem (PM - SIRTE)",
    submissionDate: "July 10, 2026 10:00 AM",
    previousProgress: 30.0,
    claimedProgress: 60.0,
    priority: "standard",
    dueDate: "July 20",
    previousNotes: "Compressor station foundation inspection complete. Concrete pouring in progress.",
    deliverables: [
      { id: "del-sirte-1", description: "Compressor foundation pouring & piping connections", weight: "30.0%", status: "completed" }
    ],
    documents: [],
    auditLog: [],
    auditorNotes: "",
    status: "pending",
    invoiceNumber: "INV-SIRTE-26-001",
    invoiceAmount: 87500
  },
  {
    id: "claim-bpmc-1",
    code: "BPMC-26-001",
    title: "Terminal Depot Expansion & Logistics - Executing Phase",
    company: "Brega Petroleum Marketing Company",
    companyId: "BPMC",
    wbs: "3.0",
    claimedValue: "$32,329,361",
    numericValue: 32329361,
    submittedBy: "Eng. Salem (PM - BPMC)",
    submissionDate: "July 09, 2026 09:30 AM",
    previousProgress: 20.0,
    claimedProgress: 55.0,
    priority: "high",
    dueDate: "July 22",
    previousNotes: "Concrete ring beam completed, manifold piping setup initiated.",
    deliverables: [
      { id: "del-bpmc-1", description: "Concrete ring beam pouring & fuel pump mounting", weight: "35.0%", status: "completed" }
    ],
    documents: [],
    auditLog: [],
    auditorNotes: "",
    status: "pending",
    invoiceNumber: "INV-BPMC-26-001",
    invoiceAmount: 300000
  },
  {
    id: "claim-zueitina-1",
    code: "ZUEITINA-26-001",
    title: "Crude Storage Tank Restoration & Port Logistics - Executing Phase",
    company: "Zueitina Oil Company",
    companyId: "ZUEITINA",
    wbs: "3.0",
    claimedValue: "$17,511,737",
    numericValue: 17511737,
    submittedBy: "Eng. Salem (PM - ZUEITINA)",
    submissionDate: "July 08, 2026 11:45 AM",
    previousProgress: 15.0,
    claimedProgress: 45.0,
    priority: "standard",
    dueDate: "July 25",
    previousNotes: "Floating roof repairs ongoing. Plates replaced.",
    deliverables: [
      { id: "del-zueitina-1", description: "Sandblasting & bottom plate welding", weight: "30.0%", status: "completed" }
    ],
    documents: [],
    auditLog: [],
    auditorNotes: "",
    status: "pending",
    invoiceNumber: "INV-ZUEITINA-26-001",
    invoiceAmount: 162500
  },
  {
    id: "claim-harouge-1",
    code: "HAROUGE-26-001",
    title: "Amal Desert Field Flowline Repair & Pipeline Tie-in - Executing Phase",
    company: "Harouge Oil Operations",
    companyId: "HAROUGE",
    wbs: "3.0",
    claimedValue: "$12,123,510",
    numericValue: 12123510,
    submittedBy: "Eng. Salem (PM - HAROUGE)",
    submissionDate: "July 07, 2026 03:20 PM",
    previousProgress: 25.0,
    claimedProgress: 50.0,
    priority: "standard",
    dueDate: "July 30",
    previousNotes: "Flowline segments welded and desert trenching completed.",
    deliverables: [
      { id: "del-harouge-1", description: "Desert trenching & segment welding", weight: "25.0%", status: "completed" }
    ],
    documents: [],
    auditLog: [],
    auditorNotes: "",
    status: "pending",
    invoiceNumber: "INV-HAROUGE-26-001",
    invoiceAmount: 112500
  },
  {
    id: "claim-akakus-1",
    code: "AKAKUS-26-001",
    title: "Sharara Field Wellhead Drilling Logistics - Executing Phase",
    company: "Akakus Oil Operations",
    companyId: "AKAKUS",
    wbs: "3.0",
    claimedValue: "$7,543,518",
    numericValue: 7543518,
    submittedBy: "Eng. Salem (PM - AKAKUS)",
    submissionDate: "July 06, 2026 01:10 PM",
    previousProgress: 10.0,
    claimedProgress: 40.0,
    priority: "standard",
    dueDate: "July 24",
    previousNotes: "Access roads cleared and stabilized. Camp building erected.",
    deliverables: [
      { id: "del-akakus-1", description: "Sand stabilization & camp building erection", weight: "30.0%", status: "completed" }
    ],
    documents: [],
    auditLog: [],
    auditorNotes: "",
    status: "pending",
    invoiceNumber: "INV-AKAKUS-26-001",
    invoiceAmount: 84000
  },
  {
    id: "claim-rasco-1",
    code: "RASCO-26-001",
    title: "Petrochemical Complex Thermal Cracking Unit Overhaul - Executing Phase",
    company: "Ras Lanuf Oil & Gas Processing",
    companyId: "RASCO",
    wbs: "3.0",
    claimedValue: "$25,594,077",
    numericValue: 25594077,
    submittedBy: "Eng. Salem (PM - RASCO)",
    submissionDate: "July 05, 2026 10:15 AM",
    previousProgress: 45.0,
    claimedProgress: 70.0,
    priority: "high",
    dueDate: "July 21",
    previousNotes: "Steam line insulation completed and valves replaced.",
    deliverables: [
      { id: "del-rasco-1", description: "Valve mounting & internal tray upgrades", weight: "25.0%", status: "completed" }
    ],
    documents: [],
    auditLog: [],
    auditorNotes: "",
    status: "pending",
    invoiceNumber: "INV-RASCO-26-001",
    invoiceAmount: 190000
  },
  {
    id: "claim-zawia-1",
    code: "ZAWIA-26-001",
    title: "Refinery Distillation Column Tray Upgrades - Executing Phase",
    company: "Zawia Oil Refining Company",
    companyId: "ZAWIA",
    wbs: "3.0",
    claimedValue: "$49,841,098",
    numericValue: 49841098,
    submittedBy: "Eng. Salem (PM - ZAWIA)",
    submissionDate: "July 04, 2026 09:00 AM",
    previousProgress: 15.0,
    claimedProgress: 40.0,
    priority: "high",
    dueDate: "July 29",
    previousNotes: "Sieve trays installed in main distillation column.",
    deliverables: [
      { id: "del-zawia-1", description: "Sieve trays installation & head insulation", weight: "25.0%", status: "completed" }
    ],
    documents: [],
    auditLog: [],
    auditorNotes: "",
    status: "pending",
    invoiceNumber: "INV-ZAWIA-26-001",
    invoiceAmount: 370000
  },
  {
    id: "claim-sonatrach-1",
    code: "SONATRACH-26-001",
    title: "Exploration Block NC-100 3D Seismic Surveying - Executing Phase",
    company: "Sonatrach",
    companyId: "SONATRACH",
    wbs: "3.0",
    claimedValue: "$39,064,644",
    numericValue: 39064644,
    submittedBy: "Eng. Salem (PM - SONATRACH)",
    submissionDate: "July 03, 2026 04:30 PM",
    previousProgress: 10.0,
    claimedProgress: 35.0,
    priority: "standard",
    dueDate: "July 31",
    previousNotes: "Seismic trailer setup and dynamic lines laid.",
    deliverables: [
      { id: "del-sonatrach-1", description: "Geophone line laying & source truck calibration", weight: "25.0%", status: "completed" }
    ],
    documents: [],
    auditLog: [],
    auditorNotes: "",
    status: "pending",
    invoiceNumber: "INV-SONATRACH-26-001",
    invoiceAmount: 290000
  },
  {
    id: "claim-eni-1",
    code: "ENI-26-001",
    title: "Offshore Platform Structural Safety Audits & Subsea Hookup - Executing Phase",
    company: "Eni North Africa B.V.",
    companyId: "ENI",
    wbs: "3.0",
    claimedValue: "$15,625,858",
    numericValue: 15625858,
    submittedBy: "Eng. Salem (PM - ENI)",
    submissionDate: "July 02, 2026 11:15 AM",
    previousProgress: 50.0,
    claimedProgress: 75.0,
    priority: "high",
    dueDate: "July 26",
    previousNotes: "Structural welds reinforced, subsea valve hookup finalized.",
    deliverables: [
      { id: "del-eni-1", description: "Platform weld reinforcements & subsea valve tie-in", weight: "25.0%", status: "completed" }
    ],
    documents: [],
    auditLog: [],
    auditorNotes: "",
    status: "pending",
    invoiceNumber: "INV-ENI-26-001",
    invoiceAmount: 145000
  },
  {
    id: "claim-npcc-1",
    code: "NPCC-26-001",
    title: "Offshore Pipeline Trenching & Jacket Installation - Executing Phase",
    company: "National Petroleum Construction Company",
    companyId: "NPCC",
    wbs: "3.0",
    claimedValue: "$44,452,871",
    numericValue: 44452871,
    submittedBy: "Eng. Salem (PM - NPCC)",
    submissionDate: "July 01, 2026 02:20 PM",
    previousProgress: 30.0,
    claimedProgress: 55.0,
    priority: "standard",
    dueDate: "July 28",
    previousNotes: "Jacket structure successfully launched and pile driving completed.",
    deliverables: [
      { id: "del-npcc-1", description: "Jacket structure launching & pile driving", weight: "25.0%", status: "completed" }
    ],
    documents: [],
    auditLog: [],
    auditorNotes: "",
    status: "pending",
    invoiceNumber: "INV-NPCC-26-001",
    invoiceAmount: 412500
  },
  {
    id: "claim-jowfe-1",
    code: "JOWFE-26-001",
    title: "Drilling Fluids & Bentonite Quality Control Facility - Executing Phase",
    company: "Jowfe Oil Technology",
    companyId: "JOWFE",
    wbs: "3.0",
    claimedValue: "$5,927,049",
    numericValue: 5927049,
    submittedBy: "Eng. Salem (PM - JOWFE)",
    submissionDate: "June 30, 2026 10:45 AM",
    previousProgress: 15.0,
    claimedProgress: 45.0,
    priority: "standard",
    dueDate: "July 24",
    previousNotes: "Spectrometer and lab ventilation systems installed.",
    deliverables: [
      { id: "del-jowfe-1", description: "Spectrometer install & warehouse layouts", weight: "30.0%", status: "completed" }
    ],
    documents: [],
    auditLog: [],
    auditorNotes: "",
    status: "pending",
    invoiceNumber: "INV-JOWFE-26-001",
    invoiceAmount: 66000
  },
  {
    id: "claim-taknia-1",
    code: "TAKNIA-26-001",
    title: "Bahr Essalam Phase II FEED Engineering Studies - Executing Phase",
    company: "Taknia Libya Engineering",
    companyId: "TAKNIA",
    wbs: "3.0",
    claimedValue: "$11,045,865",
    numericValue: 11045865,
    submittedBy: "Eng. Salem (PM - TAKNIA)",
    submissionDate: "June 29, 2026 09:30 AM",
    previousProgress: 20.0,
    claimedProgress: 50.0,
    priority: "standard",
    dueDate: "July 27",
    previousNotes: "Draft PFD drawings and WBS setup finalized.",
    deliverables: [
      { id: "del-taknia-1", description: "PFD drawings updates & draft specs", weight: "30.0%", status: "completed" }
    ],
    documents: [],
    auditLog: [],
    auditorNotes: "",
    status: "pending",
    invoiceNumber: "INV-TAKNIA-26-001",
    invoiceAmount: 123000
  },
  {
    id: "claim-ndwc-1",
    code: "NDWC-26-001",
    title: "Developmental Rig Mobilization & Well Workover - Executing Phase",
    company: "National Drilling & Workover Company",
    companyId: "NDWC",
    wbs: "3.0",
    claimedValue: "$52,535,211",
    numericValue: 52535211,
    submittedBy: "Eng. Salem (PM - NDWC)",
    submissionDate: "June 28, 2026 04:00 PM",
    previousProgress: 10.0,
    claimedProgress: 35.0,
    priority: "high",
    dueDate: "July 30",
    previousNotes: "Rig mast raised and BOP installation complete.",
    deliverables: [
      { id: "del-ndwc-1", description: "Rig mast raising & BOP installation", weight: "25.0%", status: "completed" }
    ],
    documents: [],
    auditLog: [],
    auditorNotes: "",
    status: "pending",
    invoiceNumber: "INV-NDWC-26-001",
    invoiceAmount: 487500
  },
  {
    id: "claim-nageco-1",
    code: "NAGECO-26-001",
    title: "Murzuq Basin 3D Seismic Surveying - Executing Phase",
    company: "North African Geophysical Company",
    companyId: "NAGECO",
    wbs: "3.0",
    claimedValue: "$29,635,247",
    numericValue: 29635247,
    submittedBy: "Eng. Salem (PM - NAGECO)",
    submissionDate: "June 27, 2026 11:20 AM",
    previousProgress: 10.0,
    claimedProgress: 35.0,
    priority: "standard",
    dueDate: "July 28",
    previousNotes: "Geophone grid laying and field calibration complete.",
    deliverables: [
      { id: "del-nageco-1", description: "Geophone grid laying & source calibration", weight: "25.0%", status: "completed" }
    ],
    documents: [],
    auditLog: [],
    auditorNotes: "",
    status: "pending",
    invoiceNumber: "INV-NAGECO-26-001",
    invoiceAmount: 275000
  },
  {
    id: "claim-murzuq-1",
    code: "MURZUQ-26-001",
    title: "Joint Venture Drilling Advisory & PMC - Executing Phase",
    company: "Murzuq Oil Services Limited",
    companyId: "MURZUQ",
    wbs: "3.0",
    claimedValue: "$8,621,163",
    numericValue: 8621163,
    submittedBy: "Eng. Salem (PM - MURZUQ)",
    submissionDate: "June 26, 2026 10:15 AM",
    previousProgress: 20.0,
    claimedProgress: 45.0,
    priority: "standard",
    dueDate: "July 25",
    previousNotes: "Stakeholder meetings and cost-control dashboards implemented.",
    deliverables: [
      { id: "del-murzuq-1", description: "Stakeholder workshop coordination", weight: "25.0%", status: "completed" }
    ],
    documents: [],
    auditLog: [],
    auditorNotes: "",
    status: "pending",
    invoiceNumber: "INV-MURZUQ-26-001",
    invoiceAmount: 80000
  },
  {
    id: "claim-lifeco-1",
    code: "LIFECO-26-001",
    title: "Urea Fertilizer Plant Compressor Overhaul - Executing Phase",
    company: "Libyan Fertilizer Company",
    companyId: "LIFECO",
    wbs: "3.0",
    claimedValue: "$23,708,198",
    numericValue: 23708198,
    submittedBy: "Eng. Salem (PM - LIFECO)",
    submissionDate: "June 25, 2026 09:00 AM",
    previousProgress: 15.0,
    claimedProgress: 40.0,
    priority: "high",
    dueDate: "July 29",
    previousNotes: "Rotor dismantling and replacement of seal sets complete.",
    deliverables: [
      { id: "del-lifeco-1", description: "Rotor dismantle & high-pressure seal swaps", weight: "25.0%", status: "completed" }
    ],
    documents: [],
    auditLog: [],
    auditorNotes: "",
    status: "pending",
    invoiceNumber: "INV-LIFECO-26-001",
    invoiceAmount: 220000
  },
  {
    id: "claim-catering-1",
    code: "CATERING-26-001",
    title: "Centralized Desert Field Catering Logistics - Executing Phase",
    company: "National Catering Company",
    companyId: "CATERING",
    wbs: "3.0",
    claimedValue: "$4,041,170",
    numericValue: 4041170,
    submittedBy: "Eng. Salem (PM - CATERING)",
    submissionDate: "June 24, 2026 04:30 PM",
    previousProgress: 50.0,
    claimedProgress: 75.0,
    priority: "standard",
    dueDate: "July 23",
    previousNotes: "Deep freeze units installed, loading bays configured.",
    deliverables: [
      { id: "del-catering-1", description: "Deep freeze install & mess hall setup", weight: "25.0%", status: "completed" }
    ],
    documents: [],
    auditLog: [],
    auditorNotes: "",
    status: "pending",
    invoiceNumber: "INV-CATERING-26-001",
    invoiceAmount: 37500
  },
  {
    id: "claim-petroair-1",
    code: "PETROAIR-26-001",
    title: "Desert Field Aviation Support & Maintenance - Executing Phase",
    company: "Petro Air Company",
    companyId: "PETROAIR",
    wbs: "3.0",
    claimedValue: "$12,931,744",
    numericValue: 12931744,
    submittedBy: "Eng. Salem (PM - PETROAIR)",
    submissionDate: "June 23, 2026 11:15 AM",
    previousProgress: 30.0,
    claimedProgress: 55.0,
    priority: "high",
    dueDate: "July 26",
    previousNotes: "Avionics system overhauled, landing gear serviced.",
    deliverables: [
      { id: "del-petroair-1", description: "Avionics maintenance & gear servicing", weight: "25.0%", status: "completed" }
    ],
    documents: [],
    auditLog: [],
    auditorNotes: "",
    status: "pending",
    invoiceNumber: "INV-PETROAIR-26-001",
    invoiceAmount: 120000
  },
  {
    id: "claim-nafusah-1",
    code: "NAFUSAH-26-001",
    title: "Hamada Field Site Preparation & Well Pad Excavations - Executing Phase",
    company: "Nafusah Oil Operations Company",
    companyId: "NAFUSAH",
    wbs: "3.0",
    claimedValue: "$26,402,311",
    numericValue: 26402311,
    submittedBy: "Eng. Salem (PM - NAFUSAH)",
    submissionDate: "June 22, 2026 02:20 PM",
    previousProgress: 10.0,
    claimedProgress: 40.0,
    priority: "standard",
    dueDate: "July 28",
    previousNotes: "Concrete anchor pouring and pad leveling complete.",
    deliverables: [
      { id: "del-nafusah-1", description: "Pad grading & concrete anchor pouring", weight: "30.0%", status: "completed" }
    ],
    documents: [],
    auditLog: [],
    auditorNotes: "",
    status: "pending",
    invoiceNumber: "INV-NAFUSAH-26-001",
    invoiceAmount: 294000
  },
  {
    id: "claim-mabruk-1",
    code: "MABRUK-26-001",
    title: "Al-Jurf Production Platform Control Systems - Executing Phase",
    company: "Mabruk Oil Operations",
    companyId: "MABRUK",
    wbs: "3.0",
    claimedValue: "$41,758,758",
    numericValue: 41758758,
    submittedBy: "Eng. Salem (PM - MABRUK)",
    submissionDate: "June 21, 2026 10:45 AM",
    previousProgress: 20.0,
    claimedProgress: 45.0,
    priority: "standard",
    dueDate: "July 24",
    previousNotes: "Server rack wiring and SCADA server installs complete.",
    deliverables: [
      { id: "del-mabruk-1", description: "PLC console upgrades & rack wiring", weight: "25.0%", status: "completed" }
    ],
    documents: [],
    auditLog: [],
    auditorNotes: "",
    status: "pending",
    invoiceNumber: "INV-MABRUK-26-001",
    invoiceAmount: 387500
  },
  {
    id: "claim-sarir-1",
    code: "SARIR-26-001",
    title: "Sarir Separator Mechanical Cleaning & Overhaul - Executing Phase",
    company: "Sarir Oil Operations Company",
    companyId: "SARIR",
    wbs: "3.0",
    claimedValue: "$21,014,085",
    numericValue: 21014085,
    submittedBy: "Eng. Salem (PM - SARIR)",
    submissionDate: "June 20, 2026 09:30 AM",
    previousProgress: 15.0,
    claimedProgress: 40.0,
    priority: "standard",
    dueDate: "July 27",
    previousNotes: "Vessel opened, separator mist extractors replaced.",
    deliverables: [
      { id: "del-sarir-1", description: "Vessel sand clearing & extractor swaps", weight: "25.0%", status: "completed" }
    ],
    documents: [],
    auditLog: [],
    auditorNotes: "",
    status: "pending",
    invoiceNumber: "INV-SARIR-26-001",
    invoiceAmount: 195000
  },
  {
    id: "claim-lerco-1",
    code: "LERCO-26-001",
    title: "Ras Lanuf Refinery Desalination Refurbishment - Executing Phase",
    company: "Libyan Emirates Refining Company",
    companyId: "LERCO",
    wbs: "3.0",
    claimedValue: "$30,982,304",
    numericValue: 30982304,
    submittedBy: "Eng. Salem (PM - LERCO)",
    submissionDate: "June 19, 2026 04:00 PM",
    previousProgress: 10.0,
    claimedProgress: 40.0,
    priority: "high",
    dueDate: "July 30",
    previousNotes: "Evaporator plates swapped, water lines welded.",
    deliverables: [
      { id: "del-lerco-1", description: "Plate swaps & heat exchanger cleaning", weight: "30.0%", status: "completed" }
    ],
    documents: [],
    auditLog: [],
    auditorNotes: "",
    status: "pending",
    invoiceNumber: "INV-LERCO-26-001",
    invoiceAmount: 345000
  },
  {
    id: "claim-clinic-1",
    code: "CLINIC-26-001",
    title: "Main Oil Clinic HVAC HEPA Upgrade - Executing Phase",
    company: "Oil Clinic",
    companyId: "CLINIC",
    wbs: "3.0",
    claimedValue: "$6,735,283",
    numericValue: 6735283,
    submittedBy: "Eng. Salem (PM - CLINIC)",
    submissionDate: "June 18, 2026 11:20 AM",
    previousProgress: 40.0,
    claimedProgress: 65.0,
    priority: "standard",
    dueDate: "July 28",
    previousNotes: "Air handlers installed, ductwork sealed.",
    deliverables: [
      { id: "del-clinic-1", description: "Ductwork sealing & handler swaps", weight: "25.0%", status: "completed" }
    ],
    documents: [],
    auditLog: [],
    auditorNotes: "",
    status: "pending",
    invoiceNumber: "INV-CLINIC-26-001",
    invoiceAmount: 62500
  },
  {
    id: "claim-stcpi-1",
    code: "STCPI-26-001",
    title: "Technical Welding Simulator Labs - Executing Phase",
    company: "The Specific Training Center of Petroleum Industrial",
    companyId: "STCPI",
    wbs: "3.0",
    claimedValue: "$3,232,936",
    numericValue: 3232936,
    submittedBy: "Eng. Salem (PM - STCPI)",
    submissionDate: "June 17, 2026 10:15 AM",
    previousProgress: 50.0,
    claimedProgress: 80.0,
    priority: "standard",
    dueDate: "July 25",
    previousNotes: "VR welding simulator consoles assembled and wired.",
    deliverables: [
      { id: "del-stcpi-1", description: "Console assembly & simulator wiring", weight: "30.0%", status: "completed" }
    ],
    documents: [],
    auditLog: [],
    auditorNotes: "",
    status: "pending",
    invoiceNumber: "INV-STCPI-26-001",
    invoiceAmount: 36000
  },
  {
    id: "claim-ptqi-1",
    code: "PTQI-26-001",
    title: "Qualifying Institute Lab Equipment Upgrades - Executing Phase",
    company: "Petroleum Training and Qualifying Institute",
    companyId: "PTQI",
    wbs: "3.0",
    claimedValue: "$10,237,631",
    numericValue: 10237631,
    submittedBy: "Eng. Salem (PM - PTQI)",
    submissionDate: "June 16, 2026 09:00 AM",
    previousProgress: 10.0,
    claimedProgress: 45.0,
    priority: "high",
    dueDate: "July 29",
    previousNotes: "Gas chromatograph and server racks mounted.",
    deliverables: [
      { id: "del-ptqi-1", description: "Spectrometer install & server mounting", weight: "35.0%", status: "completed" }
    ],
    documents: [],
    auditLog: [],
    auditorNotes: "",
    status: "pending",
    invoiceNumber: "INV-PTQI-26-001",
    invoiceAmount: 133000
  },
  {
    id: "claim-prc-1",
    code: "PRC-26-001",
    title: "Geological Core Sample Scanning Studies - Executing Phase",
    company: "Petroleum Research Center",
    companyId: "PRC",
    wbs: "3.0",
    claimedValue: "$4,849,404",
    numericValue: 4849404,
    submittedBy: "Eng. Salem (PM - PRC)",
    submissionDate: "June 15, 2026 04:30 PM",
    previousProgress: 30.0,
    claimedProgress: 60.0,
    priority: "standard",
    dueDate: "July 23",
    previousNotes: "Reservoir core scanning server mounted.",
    deliverables: [
      { id: "del-prc-1", description: "Scanner installation & DB server setups", weight: "30.0%", status: "completed" }
    ],
    documents: [],
    auditLog: [],
    auditorNotes: "",
    status: "pending",
    invoiceNumber: "INV-PRC-26-001",
    invoiceAmount: 54000
  },
  {
    id: "claim-sipt-1",
    code: "SIPT-26-001",
    title: "Southern Engineering Training Workshops - Executing Phase",
    company: "Sebha Institute of Petroleum Technology",
    companyId: "SIPT",
    wbs: "3.0",
    claimedValue: "$3,771,759",
    numericValue: 3771759,
    submittedBy: "Eng. Salem (PM - SIPT)",
    submissionDate: "June 14, 2026 11:15 AM",
    previousProgress: 20.0,
    claimedProgress: 50.0,
    priority: "high",
    dueDate: "July 26",
    previousNotes: "Practical workshop tools and drilling simulators installed.",
    deliverables: [
      { id: "del-sipt-1", description: "Practical tools and simulator setups", weight: "30.0%", status: "completed" }
    ],
    documents: [],
    auditLog: [],
    auditorNotes: "",
    status: "pending",
    invoiceNumber: "INV-SIPT-26-001",
    invoiceAmount: 42000
  },
  {
    id: "claim-api-1",
    code: "API-26-001",
    title: "Oasis Region Safety Training H2S Simulator - Executing Phase",
    company: "Ajdabiya Petroleum Institute",
    companyId: "API",
    wbs: "3.0",
    claimedValue: "$2,559,409",
    numericValue: 2559409,
    submittedBy: "Eng. Salem (PM - API)",
    submissionDate: "June 13, 2026 02:20 PM",
    previousProgress: 50.0,
    claimedProgress: 85.0,
    priority: "standard",
    dueDate: "July 28",
    previousNotes: "Toxic gas simulator simulation chamber constructed.",
    deliverables: [
      { id: "del-api-1", description: "Simulator chamber construction & alarms", weight: "35.0%", status: "completed" }
    ],
    documents: [],
    auditLog: [],
    auditorNotes: "",
    status: "pending",
    invoiceNumber: "INV-API-26-001",
    invoiceAmount: 33250
  }
];
